### PR TITLE
github: add issue templates

### PR DESCRIPTION
**Pull request by diamante0018**

### CODE REVIEW

**Review by momo5502 — COMMENTED** [review]
I think there is way too much text in the template. people are not gonna read that.

**Comment by diamante0018** [comment]
And I thought they were pretty small in size 🥲
I have tested this, the get help document fits well in a small chunk of the screen after the markdown was applied. I honestly don't think of anything that can be removed because it looks like me it's pretty minimal

**Comment by diamante0018** [comment]
I looked at iw4x, we have used this template for months. Everyone that opened an issue used the template correctly. Evidence suggests that the length is fine.

**Comment by diamante0018** [comment]
@momo5502 I removed one small thing. Now the document is very minimal.

**Review by momo5502 — COMMENTED** [review]
"Evidence suggests that the length is fine."
If that's the case, it's fine

**Review by momo5502 — APPROVED** [review]

**Pull request merged**
