### PR TITLE
improved motd for zombies

### LINKED ISSUE #155: Add improved MOTD in zombies
Currently default AW motd is showing up in zombies.

image

### PR DESCRIPTION
**Pull request by Brentdevent**
This seems to fix #155 

image

### CODE REVIEW

**Comment by mjkzy** [comment]
this is just a question for my own curiosity but how did this little bit fix zm but it was working for mp originally? either way very nice PR

**Comment by mjkzy** [comment]
@Brentdevent ah, so im assuming ``.*\\`` means that anything can be in front of it

**Comment by Brentdevent** [comment]
> @Brentdevent ah, so im assuming `.*\\` means that anything can be in front of it

Yea indeed

**Review by momo5502 — APPROVED** [review]

**Comment by momo5502** [comment]
Technically, the image of the day can also be loaded by providing the proper publisher file. But as it works right now, let's just keep it this way 😂

**Pull request merged**
