### PR TITLE
didyouknow does not reset #163

### LINKED ISSUE #163: sv_motd only working on first loading screen shown
A custom sv_motd is only shown on the first loading screen but not after the map gets changed for example through the map rotation.

### PR DESCRIPTION
**Pull request by mjkzy**
don't know why we clear sv_motd if a ``getInfo`` request is only sent the first time the player connects to the server, which defines sv_motd

fixes #163

### CODE REVIEW

**Comment by Joelrau** [comment]
We clear it because if you go into a private match after joining a server with a custom sv_motd it will show it.

**Review by Joelrau — APPROVED** [review]
LGTM

**Review by momo5502 — COMMENTED** [review]
Is cl_disconnect called if the client drops using a longjmp? For example if a critical error occurs and the game calls Com_Error with error drop for example?

**Comment by mjkzy** [comment]
@momo5502 guess not. does CL_Disconnect not get called, even if it give's a error? isn't that something Com_Error should do? because if it doesn't get called, then forwarding the ``disconnect`` command and packet to the server wouldn't happen either by the looks of it.

**Comment by Joelrau** [comment]
Actually, wouldn't it be fine just add a check for if SV_Loaded is true then clear sv_motd in didyouknow stub?

**Comment by mjkzy** [comment]
Does SV_Loaded only return true if connecting to a server?

**Comment by mjkzy** [comment]
nvm just gonna close this for now - will reopen when i figure out a better solution for all this. i thought maybe calling the disconnect stuff on a error would possibly fix it but now it seems like com_error isn't even getting called

**Pull request closed without merging**
